SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, 
COUNT(DISTINCT O.USER_ID) PUCHASED_USERS,
ROUND( (COUNT(DISTINCT O.USER_ID) /
    (SELECT COUNT(U.USER_ID)
     FROM USER_INFO U
     WHERE YEAR(U.JOINED) = 2021)), 1) PUCHASED_RATIO
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
AND YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
