SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A ON (B.AUTHOR_ID = A.AUTHOR_ID)
INNER JOIN BOOK_SALES S ON (B.BOOK_ID = S.BOOK_ID)
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC