SELECT FLAVOR
FROM FIRST_HALF F
INNER JOIN ( SELECT SUM(TOTAL_ORDER) JULY_TOTAL, SHIPMENT_ID
             FROM JULY
             GROUP BY FLAVOR ) J ON F.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY JULY_TOTAL+TOTAL_ORDER DESC
LIMIT 3