SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d'),
CASE WHEN DATEDIFF(OUT_DATE, '2022-05-01') <= 0 THEN '출고완료'
WHEN DATEDIFF(OUT_DATE, '2022-05-01') IS NULL THEN '출고미정'
ELSE '출고대기' END '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID